import React from "react";
import SectionContainer from "./section_container";
import { impactList } from "@/utils/constants";
import Image from "next/image";
import { cn } from "@/lib/utils";


const ImpactSection = () => {
  return (
    <SectionContainer
      title={
        <p className="font-helvetica-display">
          From Ideas to Impact:
          <br />
          Scale your business with ZatiqEasy
        </p>
      }
    >
      <div className="w-full space-y-3">
        <div
          className="bg-center bg-cover rounded-[24px] overflow-clip"
          style={{
            backgroundImage: "url(/assets/images/gradient_bg.png)",
          }}
        >
          <div
            className="space-y-2 text-center bg-black/50"
            style={{
              backdropFilter: "blur(30px)",
            }}
          >
            <div className="p-3 md:py-6 md:px-0 grid grid-cols-1 md:grid-cols-3 divide-y md:divide-x md:divide-y-0 divide-white divide-opacity-15 ">
              {impactList?.map((item, index) => (
                <div
                  key={index}
                  className={cn("w-full", {
                    "pb-6 md:pb-0 md:px-6": index === 0,
                    "py-6 md:py-0 md:px-6": index > 0 && index < (impactList?.length ?? 0) - 1,
                    "pt-6 md:pt-0 md:px-6": index === (impactList?.length ?? 0) - 1,
                  })}
                >
                  <Image src={item?.imageUrl ?? ""} alt="img" width={500} height={500} className="aspect-[433/354] w-full rounded-[16px]" />

                  <div
                    className={cn("px-1 md:px-4", {
                      "pb-3": index === (impactList?.length ?? 0) - 1,
                    })}
                  >
                    <div className="font-medium text-blue-gray-100 mt-7 md:mt-10 text-start">{item?.title}</div>
                    <p className="text-blue-gray-100 mt-2 text-start font-normal">{item?.description ?? ""}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div
          className="bg-center bg-cover rounded-[24px] overflow-clip"
          style={{
            backgroundImage: "url(/assets/images/gradient_bg.png)",
          }}
        >
          <div
            className="space-y-2 text-center bg-black/50 px-6 py-8 md:py-9"
            style={{
              backdropFilter: "blur(30px)",
            }}
          >
            <p className="font-helvetica-display font-bold text-blue-gray-200 text-center text-[56px] md:text-[100px]">1500 M+</p>
            <p className="font-medium text-blue-gray-100 text-center">in revenue generated by sellers just in 2024!</p>
          </div>
        </div>
      </div>
    </SectionContainer>
  );
};

export default ImpactSection;
